### ISSUE TITLE
Injection not working with React 16.8.6

### ISSUE THREAD

**Issue by fljmayer** [gnaeus/react-ioc#4]
I followed the instructions to use React IoC in my simple project, but it's not working. I get the error below in the browser console, and when the application tries to access the injected property, it's undefined. What could be the problem?
```
index.js:1446 Error: undefined is not a valid dependency.
Please specify ES6 class as property type e.g.
class MyService {}
class Dashboard {
  @inject myService: MyService;
}
    at logError (index.esm.js:48)
    at logInvalidMetadata (index.esm.js:77)
    at injectDecorator (index.esm.js:224)
    at inject (index.esm.js:210)
    at applyDecoratedDescriptor.js:14
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (applyDecoratedDescriptor.js:13)
    at Module../src/react/Dashboard.tsx (Dashboard.tsx:27)
    at __webpack_require__ (bootstrap:786)
    at fn (bootstrap:149)
    at Module../src/react/App.tsx (App.scss?1296:45)
    at __webpack_require__ (bootstrap:786)
    at fn (bootstrap:149)
    at Module../src/react-spa.js (react-spa.js:1)
    at __webpack_require__ (bootstrap:786)
    at fn (bootstrap:149)
    at async Promise.all (:3000/index 0)
```

**Comment by gnaeus** [comment]
Sorry for a long wait. Can you provide your `tsconfig.json` file?

It should contain following options:

```json
  "experimentalDecorators": true,
  "emitDecoratorMetadata": true,
```

**Comment by thisroot** [comment]
> Sorry for a long wait. Can you provide your `tsconfig.json` file?
> 
> It should contain following options:
> 
> ```json
>   "experimentalDecorators": true,
>   "emitDecoratorMetadata": true,
> ```

It's not work. I use create-react-app with you examples. And got same error message

**Comment by thisroot** [comment]
For run this library with create-react-app. You should make any steps:
1) eject CRA
2) Add bubel plugins into package.json 
```json
 "babel": {
    "plugins": [
      "babel-plugin-transform-typescript-metadata",
      ["@babel/plugin-proposal-decorators", { "legacy": true }]
    ],
    "presets": [
      "react-app"
    ]
```

**Comment by pcdummy** [comment]
For me it was:

**tsconfig.json**:
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false
  }
}
```

Where strictPropertyInitialization was the important one.
